export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const CREATE_UNIT_OF_MEASURE = 'CREATE_UNIT_OF_MEASURE';
export const CREATE_UNIT_OF_MEASURE_SUCCESS = 'CREATE_UNIT_OF_MEASURE_SUCCESS';
export const CREATE_UNIT_OF_MEASURE_ERROR = 'CREATE_UNIT_OF_MEASURE_ERROR';
export const FETCH_ALL_UNITS_OF_MEASURE = 'FETCH_ALL_UNITS_OF_MEASURE';

export const CREATE_INGREDIENT = 'CREATE_INGREDIENT';
export const CREATE_INGREDIENT_SUCCESS = 'CREATE_INGREDIENT_SUCCESS';
export const CREATE_INGREDIENT_ERROR = 'CREATE_INGREDIENT_ERROR';
export const FETCH_ALL_INGREDIENTS = 'FETCH_ALL_INGREDIENTS';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';

export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';


export const ADD_CATEGORY_TO_NEW_RECIPE = 'ADD_CATEGORY_TO_NEW_RECIPE';
export const REMOVE_CATEGORY_FROM_NEW_RECIPE = 'REMOVE_CATEGORY_FROM_NEW_RECIPE';

export const ADD_INGREDIENT_TO_NEW_RECIPE = 'ADD_INGREDIENT_TO_NEW_RECIPE';
export const REMOVE_INGREDIENT_FROM_NEW_RECIPE = 'REMOVE_INGREDIENT_FROM_NEW_RECIPE';

export const ADD_TITLE_TO_NEW_RECIPE = 'ADD_TITLE_TO_NEW_RECIPE';
export const ADD_STEPS_TO_NEW_RECIPE = 'ADD_STEPS_TO_NEW_RECIPE';
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE = 'CREATE_RECIPE';

export const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES';
