export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const CREATE_UNIT_OF_MEASURE = 'CREATE_UNIT_OF_MEASURE';
export const CREATE_UNIT_OF_MEASURE_SUCCESS = 'CREATE_UNIT_OF_MEASURE_SUCCESS';
export const CREATE_UNIT_OF_MEASURE_ERROR = 'CREATE_UNIT_OF_MEASURE_ERROR';

export const FETCH_ALL_UNITS_OF_MEASURE = 'FETCH_ALL_UNITS_OF_MEASURE';
